import { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SymptomInput from "@/components/SymptomInput";
import AnalysisResult from "@/components/AnalysisResult";
import HowItWorks from "@/components/HowItWorks";
import DoctorContactCTA from "@/components/DoctorContactCTA";
import { Sparkles, Shield, Clock, Users } from "lucide-react";

// Mock analysis function - in production, this would call an AI API
const mockAnalyze = (symptoms: string) => {
  return new Promise<{
    conditions: Array<{
      name: string;
      probability: "high" | "medium" | "low";
      description: string;
      recommendations: string[];
    }>;
    disclaimer: string;
  }>((resolve) => {
    setTimeout(() => {
      const lowerSymptoms = symptoms.toLowerCase();
      
      const conditions = [];
      
      if (lowerSymptoms.includes("headache") || lowerSymptoms.includes("fever")) {
        conditions.push({
          name: "Common Cold or Flu",
          probability: "high" as const,
          description: "Upper respiratory infection often accompanied by headache, fever, and general malaise. Usually self-limiting and resolves within 7-10 days.",
          recommendations: [
            "Rest and stay hydrated with plenty of fluids",
            "Take over-the-counter pain relievers if needed",
            "Monitor temperature and seek care if fever exceeds 103°F",
          ],
        });
      }
      
      if (lowerSymptoms.includes("cough")) {
        conditions.push({
          name: "Bronchitis",
          probability: "medium" as const,
          description: "Inflammation of the bronchial tubes that can cause persistent cough. May be viral or bacterial in origin.",
          recommendations: [
            "Use a humidifier to ease breathing",
            "Avoid smoking and irritants",
            "Consult a doctor if cough persists beyond 3 weeks",
          ],
        });
      }
      
      if (lowerSymptoms.includes("fatigue") || lowerSymptoms.includes("weakness")) {
        conditions.push({
          name: "Vitamin Deficiency",
          probability: "low" as const,
          description: "Chronic fatigue may indicate nutritional deficiencies, particularly iron, vitamin D, or B12.",
          recommendations: [
            "Consider a balanced diet rich in vitamins",
            "Get a blood test to check vitamin levels",
            "Ensure adequate sleep (7-9 hours)",
          ],
        });
      }
      
      if (lowerSymptoms.includes("stomach") || lowerSymptoms.includes("pain")) {
        conditions.push({
          name: "Gastritis",
          probability: "medium" as const,
          description: "Inflammation of the stomach lining that can cause pain, nausea, and discomfort.",
          recommendations: [
            "Avoid spicy, acidic, or fatty foods",
            "Eat smaller, more frequent meals",
            "Seek medical attention if symptoms persist",
          ],
        });
      }
      
      if (conditions.length === 0) {
        conditions.push({
          name: "General Health Assessment",
          probability: "low" as const,
          description: "Based on your symptoms, no specific condition was identified. Your symptoms may be related to stress, lifestyle factors, or minor ailments.",
          recommendations: [
            "Maintain a healthy sleep schedule",
            "Stay physically active",
            "Monitor symptoms and consult a healthcare provider if they worsen",
          ],
        });
      }

      resolve({
        conditions,
        disclaimer: "This analysis is generated by AI and should not replace professional medical advice. Always consult with a qualified healthcare provider for proper diagnosis and treatment.",
      });
    }, 2000);
  });
};

const stats = [
  { icon: Users, value: "50K+", label: "Users Helped" },
  { icon: Shield, value: "99.9%", label: "Privacy Secure" },
  { icon: Clock, value: "<30s", label: "Analysis Time" },
];

const Index = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<{
    conditions: Array<{
      name: string;
      probability: "high" | "medium" | "low";
      description: string;
      recommendations: string[];
    }>;
    disclaimer: string;
  } | null>(null);

  const handleAnalyze = async (symptoms: string) => {
    setIsLoading(true);
    setResult(null);
    
    try {
      const analysisResult = await mockAnalyze(symptoms);
      setResult(analysisResult);
    } catch (error) {
      console.error("Analysis failed:", error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen gradient-hero">
      <Header />
      
      {/* Hero Section */}
      <main className="pt-24 pb-12 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-10 animate-fade-in">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-accent/60 text-accent-foreground text-sm font-medium mb-6">
              <Sparkles className="h-4 w-4" />
              Healix AI
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-display font-bold text-foreground mb-6 leading-tight">
              <span className="text-gradient">Healix</span> AI
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Describe your symptoms and get instant AI-powered insights about potential conditions.
              Fast, private, and always available.
            </p>
          </div>

          {/* Stats */}
          <div className="flex justify-center gap-8 mb-12">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="flex items-center justify-center gap-2 mb-1">
                  <stat.icon className="h-4 w-4 text-primary" />
                  <span className="font-display font-bold text-2xl text-foreground">{stat.value}</span>
                </div>
                <span className="text-sm text-muted-foreground">{stat.label}</span>
              </div>
            ))}
          </div>

          {/* Symptom Input Card */}
          <div className="bg-card rounded-3xl border border-border/50 shadow-card p-6 md:p-8 mb-8">
            <SymptomInput onAnalyze={handleAnalyze} isLoading={isLoading} />
          </div>

          {/* Analysis Results */}
          {result && (
            <div className="bg-card rounded-3xl border border-border/50 shadow-card p-6 md:p-8 mb-8">
              <AnalysisResult conditions={result.conditions} disclaimer={result.disclaimer} />
            </div>
          )}

          {/* Doctor Contact CTA */}
          <div className="mt-8">
            <DoctorContactCTA />
          </div>
        </div>
      </main>

      {/* How It Works Section */}
      <section id="how-it-works">
        <HowItWorks />
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
};

export default Index;
